include ./themes/Srcery.conf
# include ./themes/gruvbox_dark.conf
# include ./themes/flexoki_dark.conf

tab_bar_edge top
tab_bar_style powerline

shell_integration no-cursor

font_family family="CaskaydiaMono Nerd Font" style="SemiBold"
font_size 11.2

cursor_shape beam
cursor_blink_interval 0

background_opacity 0.97
