include ./themes/Srcery.conf
# include ./themes/gruvbox_dark.conf
# include ./themes/flexoki_dark.conf

tab_bar_edge top
tab_bar_style powerline

shell_integration no-cursor

font_family family="CaskaydiaMono Nerd Font" style="SemiBold"
font_size 11.2

cursor_shape beam
cursor_blink_interval 0

background_opacity 0.96


allow_remote_control socket-only
listen_on unix:/tmp/kitty

# kitty-scrollback.nvim Kitten alias
action_alias kitty_scrollback_nvim kitten '/home/cactr/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py'
map kitty_mod+h kitty_scrollback_nvim --nvim-args --clean --noplugin -n


# ctrl + backspace maps to ctrl + w
map ctrl+backspace send_text all \x17
