[audio-vis]
profile-cond=vid == false
lavfi-complex="[aid1]asplit=3[ao][a1][a2]; [a1]showwaves=s=1280x240:mode=p2p:colors=cyan,format=yuv420p[waves]; [a2]showspectrum=s=1280x520:mode=separate:scale=sqrt:color=channel:win_func=hann:slide=replace,format=yuv420p[spec]; [waves][spec]vstack[vo]"
