general {
  ignore_empty_input = true
}

background {
  monitor =
  path = ~/.local/share/hyprland/lock_wall.png
  blur_passes = 1
  blur_size = 5
}


# hour
label {
  monitor =
  text = cmd[update:1000] echo "<span>$(date +"%H")</span>"

  color = rgb(214, 93, 14)
  font_size = 60
  font_family = TeachingPrintDotted-OVKlp
  position = -30, 400
  halign = center
  valign = center
}

# minute
label {
  monitor =
  text = cmd[update:1000] echo "<span>$(date +":%M")</span>"
  color = rgb(214, 93, 14)
  font_size = 60
  font_family = TeachingPrintDotted-OVKlp
  position = 80, 400
  halign = center
  valign = center
}

# date
label {
  monitor =
  text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
  color = rgb(250, 227, 176)
  font_size = 19
  font_family = TeachingPrintDotted-OVKlp
  position = 35, 340
  halign = center
  valign = center
}


# profile
image {
  monitor =
  path = ~/.local/share/hyprland/avatar.png
  border_size = 2
  border_color = rgb(214, 93, 14)
  size = 220
  rounding = 50
  rotate = 0
  reload_time = -1
  reload_cmd =
  position = 35, 170
}


# user box
shape {
  monitor =
  size = 250, 50
  color = rgb(177, 98, 134)
  rounding = -1
  border_size = 0
  border_color = rgba(255, 255, 255, 1)
  rotate = 0
  xray = false
  position = 34, -20
}

# user
label {
  monitor =
  text = $USER
  color = rgba(250, 227, 176, 0.80)
  font_size = 18
  position = 37, -20
  zindex = 1
}


# password
input-field {
  monitor =
  check_text = Authenticating...
  size = 250, 50
  outline_thickness = 0
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  outer_color = rgba(250, 227, 176, 0)
  inner_color = rgb(177, 98, 134)
  font_color = rgb(250, 227, 176)
  check_color = rgb(250, 189, 47)
  fail_color = rgb(251, 73, 52)
  fade_on_empty = false
  placeholder_text = <i><span foreground="##fae3b0">   Enter Pass</span></i>
  position = 34, -80
}

# attempt counts
label {
  text = cmd[update:100] echo $((5 - $ATTEMPTS)) attempts left
  font_size = 14
  color = rgba(250, 227, 176, 0.8)
  position = 34, -130
  halign = center
  valign = center
}
