general {
  ignore_empty_input = true
}

background {
  monitor =
  path = screenshot
  blur_passes = 1
  contrast = 0.8916
  brightness = 0.8172
  vibrancy = 0.8916
  vibrancy_darkness = 0.0
}


# hour
label {
  monitor =
  text = cmd[update:1000] echo "<span>$(date +"%H")</span>"

  color = rgb(173, 48, 49)
  font_size = 60
  font_family = TeachingPrintDotted-OVKlp
  position = -30, 400
  halign = center
  valign = center
}

# minute
label {
  monitor =
  text = cmd[update:1000] echo "<span>$(date +":%M")</span>"
  color = rgb(214, 209, 209)
  font_size = 60
  font_family = TeachingPrintDotted-OVKlp
  position = 80, 400
  halign = center
  valign = center
}

# date
label {
  monitor =
  text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
  color = rgb(200, 200, 200)
  font_size = 19
  font_family = TeachingPrintDotted-OVKlp
  position = 35, 340
  halign = center
  valign = center
}


# profile
image {
  monitor =
  path = ~/.config/hypr/assets/avatar.png
  border_size = 2
  border_color = rgb(173, 48, 49)
  size = 220
  rounding = 50
  rotate = 0
  reload_time = -1
  reload_cmd =
  position = 35, 170
}


# user box
shape {
  monitor =
  size = 250, 50
  color =rgb(173, 48, 49)
  rounding = -1
  border_size = 0
  border_color = rgba(255, 255, 255, 1)
  rotate = 0
  xray = false
  position = 34, -20
}

# user
label {
  monitor =
  text = $USER
  color = rgba(216, 222, 233, 0.80)
  outline_thickness = 0
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  font_size = 18
  position = 37, -20
  zindex = 1
}


# password
input-field {
  monitor =
  check_text = Authenticating...
  size = 250, 50
  outline_thickness = 0
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  outer_color = rgba(255, 255, 255, 0)
  inner_color = rgb(173, 48, 49)
  font_color = rgb(200, 200, 200)
  fade_on_empty = false
  placeholder_text = <i><span foreground="##ffffff99">   Enter Pass</span></i>
  position = 34, -80
}

# attempt counts
label {
  text = cmd[update:100] echo $((5 - $ATTEMPTS)) attempts left
  font_size = 14
  color = rgba(255, 255, 255, 0.8)
  position = 34, -130
  halign = center
  valign = center
}
