general {
    # avoid starting multiple hyprlock instances.
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session  # lock before suspend.
    # to avoid having to press a key twice to turn on the display.
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {  # 10m: lock screen
    timeout = 600
    on-timeout = loginctl lock-session
}

listener {  # 10m30s: turn screen off
    timeout = 630
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {  # 30min: suspend
    timeout = 1800
    on-timeout = systemctl suspend
}
