#:tombi schema.strict = false
[general]
import = [
    # "~/.config/alacritty/themes/srcery.toml",
    "~/.config/alacritty/themes/gruvbox-dark-hard-contrast.toml",
    # "~/.config/alacritty/themes/gotham.toml",
    # "~/.config/alacritty/themes/flexoki_dark.toml",
]

[window]
decorations = "none"
opacity = 0.95
blur = true

[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "SemiBold" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
size = 11.2

[cursor]
style = { shape = "Beam", blinking = "Off" }
vi_mode_style = { shape = "Block", blinking = "Off" }

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
    { key = "Back", mods = "Control", "chars" = "\u0017" }
]
